name: Pin GitHub Actions

on:
  pull_request:
    paths:
      - ".github/workflows/**"
  workflow_dispatch:

jobs:
  pinact:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@83b7061638ee4956cf7545a6f7efe594e5ad0247 # v4.2.2
        with:
          persist-credentials: false
      
      - name: Pin actions
        uses: suzuki-shunsuke/pinact-action@d735505f3decf76fca3fdbb4c952e5b3eba0ffdd # v0.2.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}